services:
  - type: web
    name: light-translator
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: $PORT  # Render dynamically assigns the port
